### ISSUE TITLE
Vegan vs. Vegetarian

### ISSUE THREAD

**Issue by MrVavlo** [Barsonvenus/Memories-of-Self-Care-and-Literature#17]
I'll keep this short:

Two submod's topics are centered around Monika being a vegan.
*However* 
![image](https://github.com/Barsonvenus/Memories-of-Self-Care-and-Literature/assets/34880333/291f0ef0-a049-4919-aeb1-de1493a3e63e)
She's a vegetarian, thanks to an official topic. 
Would she even care about using a vegan mayonnaise when her reasoning to not eat meat is to not contribute to the carbon footprint?

**Comment by Barsonvenus** [comment]
Yeah, so any practicing vegetarian or vegan would know the difference between the two, and I understand that while the idea of her being vegetarian and talking about a vegan diet isn't mutually exclusive, there's definitely a weird disconnect.

I think it's very in-character for Monika to know about being vegan (Being vegan is just as a legitimate choice as being vegetarian in terms of environmental impact) so I am inclined to keep the topic in as it is actually a informative one.

This said, edits will be done to acknowledge she is canonically vegetarian and not vegan. I might add a quick few lines at the beginning of the topic and/or outright add another topic about veganism and vegetarianism.
