### ISSUE TITLE
Can´t ask Monika the time

### ISSUE THREAD

**Issue by nekoyourfriend** [Barsonvenus/Memories-of-Self-Care-and-Literature#2]
She has asked me to ask her what time it was, but I have no option to ask her. I look for it by writing it, but it still doesn´t show up.

Thank you all for this submod <3<3!

**Comment by Barsonvenus** [comment]
Have you tried exiting the game and re-entering? I find that how MAS does topics one after another may require a restart

**Comment by nekoyourfriend** [comment]
Oh okey, it appears now, thanks!
