### ISSUE TITLE
Haven't unlocked a lot of options, even tho it's been almost a month since I downloaded the submod. 

### ISSUE THREAD

**Issue by SodaAshy** [Barsonvenus/Memories-of-Self-Care-and-Literature#20]
Like, i haven't unlocked flirt topic, even tho meet cute has been unlocked, or catch her distracted, or that she has asked me to ask her what time it is, but I haven't got any option to ask time even tho it's been 2 days since 'ask the time' dialogue.

**Comment by Barsonvenus** [comment]
I've never figured it out, but there's a reoccurring experience where some people can unlock topics, and others can't- and there's no real reason or rhyme. It's hard to say what's going on.

To clarify, have you unlocked any of the random repeatable topics (as listed in "Special Repeatable Events" https://github.com/Barsonvenus/Memories-of-Self-Care-and-Literature/wiki/%22Sometimes,-I-wonder..%22-(Event-Checklist) )?

**Comment by SodaAshy** [comment]
> I've never figured it out, but there's a reoccurring experience where some people can unlock topics, and others can't- and there's no real reason or rhyme. It's hard to say what's going on.
> 
> To clarify, have you unlocked any of the random repeatable topics (as listed in "Special Repeatable Events" https://github.com/Barsonvenus/Memories-of-Self-Care-and-Literature/wiki/%22Sometimes,-I-wonder..%22-(Event-Checklist) )?

Hey, sorry for replying so late, i didnt get any notifications for some reason. After the post, i did get new topics... So i guess they'll unlock eventually. Although I do have another question. How do farewells work. Like read or gold truth i saw in the txt file in the submod. How do i get them. I dont see anything different in goodbye menu. Also, i do have unlocked special repeatable events, but innocent request (monika wants me to ask time) happened 10 days ago, still no option to ask time

**Comment by Barsonvenus** [comment]
If you'd like to provide what special repeatable events you have unlocked, I can take a look to see if the code differs from any other events.  :)

As for the farewells, those are the good-bye messages Monika gives you when you close the game. So it may take some time to unlock them all because, well, you're only saying goodbye to Monika so often.

**Comment by SodaAshy** [comment]
> If you'd like to provide what special repeatable events you have unlocked, I can take a look to see if the code differs from any other events. :)
> 
> As for the farewells, those are the good-bye messages Monika gives you when you close the game. So it may take some time to unlock them all because, well, you're only saying goodbye to Monika so often.

I've unlocked all special events except the question to the time. also, monika has never said any farewell mentioned in the wiki. I really wanted to see the request new drink topic

**Comment by Barsonvenus** [comment]
Unfortunately, we wrap around to a earlier comment; if you've unlocked everything else, there's no reason not to unlock the 'Ask the time' topic. The only natural solution would be to wait longer. :(

With this said, a solution I've been tinkering with is allowing a 'backdoor' option to unlock topics like these manually by simply running the original paired topic again. So it'll take some time to update old content with this backdoor option, but hopefully this provides a solid option going onwards.

As for the farewells, I have no idea what could be happening there. My advice would be to make sure that there is a SCLfarewells.rpy file along with the rest in the folder; that's where all the farewells are. And there shouldn't be any reason why they wouldn't trigger, a good chunk of them are unlocked by default and the code is quite simple, not unlike any regular MAS farewells. So aside from making sure the files are properly installed and maybe installing, I'm afraid I wouldn't have a clue why you wouldn't be getting any farewells.

**Comment by SodaAshy** [comment]
> Unfortunately, we wrap around to a earlier comment; if you've unlocked everything else, there's no reason not to unlock the 'Ask the time' topic. The only natural solution would be to wait longer. :(
> 
> With this said, a solution I've been tinkering with is allowing a 'backdoor' option to unlock topics like these manually by simply running the original paired topic again. So it'll take some time to update old content with this backdoor option, but hopefully this provides a solid option going onwards.
> 
> As for the farewells, I have no idea what could be happening there. My advice would be to make sure that there is a SCLfarewells.rpy file along with the rest in the folder; that's where all the farewells are. And there shouldn't be any reason why they wouldn't trigger, a good chunk of them are unlocked by default and the code is quite simple, not unlike any regular MAS farewells. So aside from making sure the files are properly installed and maybe installing, I'm afraid I wouldn't have a clue why you wouldn't be getting any farewells.

The only farewell I've unlocked is "Let's try modifying your code". I reinstalled too, but it's still the same

**Comment by Barsonvenus** [comment]
If you're seeing that farewell, then the file has installed properly. It might just be a matter of time depending on how often you play.

You can check the file itself of github to see if maybe they have triggered and you may have mistaken the dialogue for a regular MAS event: https://github.com/Barsonvenus/Memories-of-Self-Care-and-Literature/blob/Astray/SCLfarewells.rpy

For the coffee event in particular, it does require you to have previously gifted coffee, so make sure you've done that.
