### ISSUE TITLE
Only getting the lights off intro

### ISSUE THREAD

**Issue by SodaAshy** [Barsonvenus/Memories-of-Self-Care-and-Literature#21]
After downloading the submod, I've only been the lights off intro, with different dialogues.

**Comment by Barsonvenus** [comment]
should be manually fixed by accessing sclintros.rpy and deleting line 326 "override_type=True," preparing hotfix for today.

**Comment by Barsonvenus** [comment]
Update released; hopefully should fix problem. Will leave ticket open for few more days to see if issue resolved.

**Comment by Barsonvenus** [comment]
closing as no new instances of this issue have been reported.
