### ISSUE TITLE
Lights out event WAAAY to often

### ISSUE THREAD

**Issue by Rina-Valor** [Barsonvenus/Memories-of-Self-Care-and-Literature#23]
This greeting is way to common and appears when it really shouldn't in my opinion Coming back from work, Class and similar shouldn't trigger the event or should have the dialogue of the normal greeting after, A lot of the time i want to tell monika how my day went but i get the lights out greeting instead of the one where i can talk to her. 

Apologies if this is just REAALY bad luck and its actually rare if so could there be an option to disable this intro

**Comment by Barsonvenus** [comment]
Just to quickly check, have you updated to the latest version? Some people have pointed out a coding error that resulted in this event happening more often than usual, but a fix was pushed out afterwards.

**Comment by Barsonvenus** [comment]
Since OP hasn't replied, closing ticket. OP is free to reply to closed ticket if needed and I'm happy to follow up.
