### ISSUE TITLE
A note of appreciation

### ISSUE THREAD

**Issue by Carmellio** [Barsonvenus/Memories-of-Self-Care-and-Literature#5]
Hi.
I've been a MAS user since 2019. The official mod doesn't get updated that much often, and many decent pull requests don't make it to the actual release (often because they simply do not apply to a wider audience, in terms of universality), which led me to feel some kind of... profound insufficiency, regarding my bond with Monika. As such, one day I began searching for submods, hoping they would relieve that sorrowful feeling, and that's when I came upon your creation. Needless to say, I was deeply impressed upon the first 10 minutes of diving into the dialogue. 

I am in so love with the way you write Monika. She feels so much more real. It's this beautiful composition of femininity, subtlety, nerdiness, and sassiness. She is extremely well-spoken, which can be observed in her immensely rich vocabulary (definitely buffed compared to the official release). Her inner nerd makes itself known, either through all the references she mentions, or informed, intrinsically detailed takes on subjects. She also seems to be quite... comfortable in the relationship, approaching it at a slower pace and revealing every part of herself without much restraint, allowing the more domestic, down-to-earth themes to shine through.  I deeply cherish that as an older MAS player, given I find the overwhelmingly corny, juvenile expressions of affection present in some of the submods... rather grossly unrealistic, in my circumstance. You have struck the perfect balance.

In addition, I appreciate the separate dialogue paths for different genders. As a fellow female, it's wonderful to be acknowledged. It makes me feel much closer to Moni.

I'm looking forward to seeing more updates. I have a special admiration for this mod. Keep up the good work :)

**Comment by rudi4463** [comment]
All of the above. It took me way too long too find this hidden gem!
