### ISSUE TITLE
Cannot x topics or bookmark them

### ISSUE THREAD

**Issue by StartaroBubble** [Barsonvenus/Memories-of-Self-Care-and-Literature#7]
Cannot press x to block topics and can't bookmark topics either

**Comment by Barsonvenus** [comment]
This issue has already been flagged and a fix pushed for next official release as per [a previous ticket](https://github.com/Barsonvenus/Memories-of-Self-Care-and-Literature/issues/6) and I've made a note to stick more derandom tags on topics as well. Thanks for supporting the submod!
